version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: coffee_mysql

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: quanlyquancafe

    ports:
    - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql


  flask:
    build: .
    container_name: coffee_app

    ports:
      - "5000:5000"

    depends_on:
      - mysql

    restart: always

volumes:
  mysql_data:
