-- CREATE DATABASE quanlyquancafe;
-- USE quanlyquancafe;

-- -- =========================
-- -- 1. TAIKHOAN
-- -- =========================
-- CREATE TABLE TAIKHOAN (
--     MaTK INT AUTO_INCREMENT PRIMARY KEY,
--     TenDangNhap VARCHAR(50) UNIQUE NOT NULL,
--     MatKhau VARCHAR(255) NOT NULL,
--     VaiTro NVARCHAR(20) NOT NULL,
--     TrangThai NVARCHAR(20) NOT NULL,
--     DoiMK BIT DEFAULT 0
-- );

-- -- =========================
-- -- 2. NHANVIEN
-- -- =========================
-- CREATE TABLE NHANVIEN (
--     MaNV INT AUTO_INCREMENT PRIMARY KEY,
--     HoTen NVARCHAR(100) NOT NULL,
--     SDT VARCHAR(15) NOT NULL,
--     Email VARCHAR(100) UNIQUE,
--     MaTK INT NOT NULL,
--     FOREIGN KEY (MaTK) REFERENCES TAIKHOAN(MaTK)
-- );

-- -- =========================
-- -- 3. BAN
-- -- =========================
-- CREATE TABLE BAN (
--     MaBan INT AUTO_INCREMENT PRIMARY KEY,
--     TenBan NVARCHAR(50) UNIQUE NOT NULL,
--     SoChoNgoi INT NOT NULL CHECK (SoChoNgoi > 0),
--     TrangThai NVARCHAR(30) NOT NULL
-- );

-- -- =========================
-- -- 4. DANHMUC
-- -- =========================
-- CREATE TABLE DANHMUC (
--     MaDM INT AUTO_INCREMENT PRIMARY KEY,
--     TenDanhMuc NVARCHAR(100) NOT NULL
-- );

-- -- =========================
-- -- 5. MON
-- -- =========================
-- CREATE TABLE MON (
--     MaMon INT AUTO_INCREMENT PRIMARY KEY,
--     TenMon NVARCHAR(100) NOT NULL,
--     GiaBan DECIMAL(10,2) NOT NULL CHECK (GiaBan > 0),
--     TrangThai NVARCHAR(30) NOT NULL,
--     MoTa NVARCHAR(255),
--     HinhAnh VARCHAR(255),
--     MaDM INT NOT NULL,
--     FOREIGN KEY (MaDM) REFERENCES DANHMUC(MaDM)
-- );

-- -- =========================
-- -- 6. DONHANG
-- -- =========================
-- CREATE TABLE DONHANG (
--     MaDon INT AUTO_INCREMENT PRIMARY KEY,
--     NgayTao DATETIME NOT NULL,
--     TrangThai NVARCHAR(30) NOT NULL,
--     TongTien DECIMAL(10,2) NOT NULL,
--     GiamGia DECIMAL(10,2),
--     ThanhTien DECIMAL(10,2) NOT NULL,
--     MaBan INT NOT NULL,
--     MaNV INT NOT NULL,
--     FOREIGN KEY (MaBan) REFERENCES BAN(MaBan),
--     FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
-- );

-- -- =========================
-- -- 7. CHITIETDONHANG
-- -- =========================
-- CREATE TABLE CHITIETDONHANG (
--     MaCTDH INT AUTO_INCREMENT PRIMARY KEY,
--     MaDon INT NOT NULL,
--     MaMon INT NOT NULL,
--     SoLuong INT NOT NULL CHECK (SoLuong > 0),
--     DonGia DECIMAL(10,2) NOT NULL,
--     GhiChu NVARCHAR(255),
--     TrangThaiMon NVARCHAR(30) NOT NULL,
--     FOREIGN KEY (MaDon) REFERENCES DONHANG(MaDon),
--     FOREIGN KEY (MaMon) REFERENCES MON(MaMon)
-- );

-- -- =========================
-- -- 8. KHUYENMAI
-- -- =========================
-- CREATE TABLE KHUYENMAI (
--     MaKM INT AUTO_INCREMENT PRIMARY KEY,
--     MaCode VARCHAR(50) UNIQUE NOT NULL,
--     LoaiKM NVARCHAR(20) NOT NULL,
--     GiaTri DECIMAL(10,2) NOT NULL,
--     NgayHetHan DATETIME,
--     TrangThai NVARCHAR(20) NOT NULL
-- );

-- -- =========================
-- -- 9. THANHTOAN
-- -- =========================
-- CREATE TABLE THANHTOAN (
--     MaTT INT AUTO_INCREMENT PRIMARY KEY,
--     MaDon INT UNIQUE NOT NULL,
--     MaKM INT,
--     PhuongThuc NVARCHAR(30) NOT NULL,
--     SoTienVao DECIMAL(10,2),
--     TienThoi DECIMAL(10,2),
--     VAT DECIMAL(10,2),
--     NgayThanhToan DATETIME NOT NULL,
--     FOREIGN KEY (MaDon) REFERENCES DONHANG(MaDon),
--     FOREIGN KEY (MaKM) REFERENCES KHUYENMAI(MaKM)
-- );

-- -- =========================
-- -- 10. NGUYENLIEU
-- -- =========================
-- CREATE TABLE NGUYENLIEU (
--     MaNL INT AUTO_INCREMENT PRIMARY KEY,
--     TenNL NVARCHAR(100) NOT NULL,
--     DonViTinh NVARCHAR(20) NOT NULL,
--     SoLuongTon DECIMAL(10,2) NOT NULL CHECK (SoLuongTon >= 0),
--     DinhMucTonKho DECIMAL(10,2) NOT NULL,
--     SoLuongTruTam DECIMAL(10,2) DEFAULT 0
-- );

-- -- =========================
-- -- 11. CONGTHUC
-- -- =========================
-- CREATE TABLE CONGTHUC (
--     MaMon INT NOT NULL,
--     MaNL INT NOT NULL,
--     SoLuongSuDung DECIMAL(10,2) NOT NULL,
--     PRIMARY KEY (MaMon, MaNL),
--     FOREIGN KEY (MaMon) REFERENCES MON(MaMon),
--     FOREIGN KEY (MaNL) REFERENCES NGUYENLIEU(MaNL)
-- );

-- -- =========================
-- -- 12. LICHSUDONHANG
-- -- =========================
-- CREATE TABLE LICHSUDONHANG (
--     MaLS INT AUTO_INCREMENT PRIMARY KEY,
--     MaDon INT NOT NULL,
--     MaNV INT NOT NULL,
--     HanhDong NVARCHAR(50) NOT NULL,
--     NoiDung NVARCHAR(255),
--     ThoiGian DATETIME NOT NULL,
--     FOREIGN KEY (MaDon) REFERENCES DONHANG(MaDon),
--     FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
-- );

-- -- =========================
-- -- 13. PHIEUNHAP
-- -- =========================
-- CREATE TABLE PHIEUNHAP (
--     MaPN INT AUTO_INCREMENT PRIMARY KEY,
--     MaNL INT NOT NULL,
--     MaNV INT NOT NULL,
--     SoLuong DECIMAL(10,2) NOT NULL,
--     GiaNhap DECIMAL(10,2) NOT NULL,
--     NgayNhap DATETIME NOT NULL,
--     FOREIGN KEY (MaNL) REFERENCES NGUYENLIEU(MaNL),
--     FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
-- );

-- -- =========================
-- -- 14. DATBAN
-- -- =========================
-- CREATE TABLE DATBAN (
--     MaDatBan INT AUTO_INCREMENT PRIMARY KEY,
--     MaBan INT NOT NULL,
--     TenKhach NVARCHAR(100) NOT NULL,
--     SDT VARCHAR(15) NOT NULL,
--     GioDen DATETIME NOT NULL,
--     SoNguoi INT NOT NULL CHECK (SoNguoi > 0),
--     FOREIGN KEY (MaBan) REFERENCES BAN(MaBan)
-- );